name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./src
    - name: Build
      run: dotnet build ./src -c Release
    - name: Publish
      run: dotnet publish ./src/Blazor.Playground.UI -c Release -o $GITHUB_WORKSPACE/publish --no-restore
    - name: Deploy app
      uses: Azure/cli@v1.0.0
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob upload-batch -s $GITHUB_WORKSPACE/publish -d \$web --connection-string "${{ secrets.STORAGE_CONNECTION }}"
